use test_assignment_1;

ALTER TABLE GroupAccount
ADD FOREIGN KEY (GroupID) REFERENCES `Group` (GroupID) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (AccountID) REFERENCES `Account` (AccountID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `Account`
ADD FOREIGN KEY (DepartmentID) REFERENCES `Department` (DepartmentID) ON DELETE CASCADE ON UPDATE CASCADE ,
ADD FOREIGN KEY (PositionID) REFERENCES `Position` (PositionID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `Question`
ADD FOREIGN KEY (TypeID) REFERENCES `TypeQuestion`(TypeID) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (CategoryID) REFERENCES `CategoryQuestion`(CategoryID) ON DELETE CASCADE ON UPDATE CASCADE
;

ALTER TABLE `Answer`
ADD FOREIGN KEY (QuestionID) REFERENCES `Question`(QuestionID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `ExamQuestion`
ADD FOREIGN KEY (ExamID) REFERENCES `Exam`(ExamID),
ADD FOREIGN KEY (QuestionID) REFERENCES `Question`(QuestionID) ON DELETE CASCADE ON UPDATE CASCADE
;